### ISSUE TITLE
Expecting a directory but might find a file

### ISSUE THREAD

**Issue by roadelou** [theodumont/video-logging#4]
At various points in the [src/video-logging.py](https://github.com/theodumont/video-logging/blob/master/src/video_logging.py) file, the functions will check if a directory already exist, and create it if it doesn't. The current implementation is :

```python
# snippet from move_to_trash
if not os.path.isdir('Trash'):
  os.mkdir('./Trash')
os.rename(file, os.path.join('Trash', file))
```

The issue with this one quite obvious : __if I have a file called "Trash"__ in my current working directory, then os.path.isdir('Trash') will return False because a regular file is not a directory. Thus, python will try to create a directory with the same name as file, which the OS will _politely decline_.

This is not a huge deal, but you might want to do some error handling here. You probably want to combine this with __os.path.exists__ to test all the variants :

```python
if os.path.exists('Trash'):
    if os.path.isdir('Trash'):
      # Take action if Trash is a directory
      pass
    else:
      # Take action if Trash is a regular file
      pass
else:
  # Take action if file does not exist
  pass
```

This might seem like a weird edge case, but __on Linux files without extensions are common place__. Thus, it is not a bad practice to __be cautious when moving files to a directory__.

**Comment by theodumont** [comment]
Yes, indeed!
I corrected this. When encountering a file named like `Trash`, `Audio` or another folder using a default directory name, the tool now politely asks the user to change the default names of the tool's directories in the `data.yaml` file.

However, because of the structure of the codes, the tool __may stop in the middle of a process__ (like sorting files) if it encounters a wrongly named file. It's not a big deal and nothing will be broken because of this. The user will just have to change the default name in `data.yaml` and execute his command again.
